### ISSUE TITLE
Use config file to protect authentication data

### ISSUE THREAD

**Issue by qubist** [holochain/soa-scraper#5]
In my understanding this is what needs to happen:
* env module needs to be used to manage environment variables
* Issues should be created using GitHub API from the `simpleserver.js` file instead of the `create-issue.js` file since `create-issue.js` is run from the web and doesn't support the `require` method, while `simpleserver.js` does. This means we can use our env variables in `simpleserver.js` to safely authenticate.
* For issues to be created from `simpleserver.js`, they must be sent to the server by `create-issue.js` which is running on the web (Miro). In dev, this should be possible using an HTTP POST to the ngrok URL of the serer.
* 
I request help with this.

**Comment by Connoropolous** [comment]
@qubist I can offer a bit of help here...

**Comment by Connoropolous** [comment]
For the environment variable aspect... you'll want to generate a Github token for Github calls.

This is the lib to take a look into: https://www.npmjs.com/package/dotenv

Imagine the env var name is `GH_TOKEN` in a `.env` file you might set `GH_TOKEN=1nasdkfj...`

In the nodejs `simpleserver.js` you would reference it by `process.env.GH_TOKEN`

**Comment by Connoropolous** [comment]
For the HTTP calls... 

I would recommend using a POST request with [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) for the client side JS call to the ngrok/simpleserver

For the simpleserver pass through to GH... there's lots of nice simple HTTP libs, I would recommend [request](https://www.npmjs.com/package/request)
Take the `body` of the data passed to the endpoint, and potentially just pass it straight to the github API call that needs to be made

**Comment by qubist** [comment]
Thanks @Connoropolous!

**Comment by qubist** [comment]
Whoops; this isn't resolved until we commit 🙃

**Comment by qubist** [comment]
Resolved by 019b0ea93050857184e605cec063247e53901b65
